services:
  django:
    restart: unless-stopped
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - mode: ingress
        target: 8000
        # published: 8000 # uncomment for local dev
    env_file:
      - app/.env
    #deploy:
    #  resources:
    #    reservations:
    #      memory: 256M
