name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    environment: playground
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:

      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Environment Variables
        run:  |
          cp app/.env.example app/.env
          sed -i "s/^DJANGO_SECRET_KEY=.*$/DJANGO_SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }}/" app/.env

      - name: Deploy
        uses: DefangLabs/defang-github-action@v1.1.0
